const mongoose = require("mongoose");

const cardSchema = new mongoose.Schema({
  object: String,
  id: String,
  oracle_id: String,
  multiverse_ids: Array,
  mtgo_id: Number,
  tcgplayer_id: Number,
  cardmarket_id: Number,
  name: String,
  lang: String,
  released_at: String,
  uri: String,
  scryfall_uri: String,
  layout: String,
  highres_image: Boolean,
  image_uris: Object,
  mana_cost: String,
  cmc: Number,
  type_line: String,
  oracle_text: String,
  power: String,
  toughness: String,
  colors: Array,
  color_identity: Array,
  keywords: Array,
  legalities: Object,
  games: Array,
  reserved: Boolean,
  foil: Boolean,
  nonfoil: Boolean,
  oversized: Boolean,
  promo: Boolean,
  reprint: Boolean,
  variation: Boolean,
  set: String,
  set_name: String,
  set_type: String,
  set_uri: String,
  set_search_uri: String,
  scryfall_set_uri: String,
  rulings_uri: String,
  prints_search_uri: String,
  collector_number: String,
  digital: Boolean,
  rarity: String,
  flavor_text: String,
  card_back_id: String,
  artist: String,
  artist_ids: Array,
  illustration_id: String,
  border_color: String,
  frame: String,
  full_art: Boolean,
  textless: Boolean,
  booster: Boolean,
  story_spotlight: Boolean,
  edhrec_rank: Number,
  prices: Object,
  related_uris: Object,
  purchase_uris: Object,
});

module.exports = mongoose.model("Cards", cardSchema);
